/*
 * @Description: 
 * @Author: alon
 * @Date: 2021-10-06 17:19:46
 * @LastEditTime: 2021-11-04 15:33:49
 * @LastEditors: alon
 */
// import {IMG_URL} from '@common/config';

// icons start //
const bottomNavIcon = {
  tab_home: require('@images/bottomNavIcon/tab_home.png'),
  tab_home_activate: require('@images/bottomNavIcon/tab_home_activate.png'),
  tab_favorite: require('@images/bottomNavIcon/tab_favorite.png'),
  tab_favorite_active: require('@images/bottomNavIcon/tab_favorite_active.png'),
  tab_mail_active: require('@images/bottomNavIcon/tab_mail_active.png'),
  tab_mail: require('@images/bottomNavIcon/tab_mail.png'),
  tab_personal_active: require('@images/bottomNavIcon/tab_personal_active.png'),
  tab_personal: require('@images/bottomNavIcon/tab_personal.png'),
  tab_reserve_active: require('@images/bottomNavIcon/tab_reserve_active.png'),
  tab_reserve: require('@images/bottomNavIcon/tab_reserve.png'),
};

const common = {
  goBack: require('@images/common/icon_goback.png'),
  titleCom_share_black: require('@images/common/titleCom_share_black.png'),
  goBack_black: require('@images/common/icon_advanced_options_back.png'),
  region_close: require('@images/common/icon_advanced_options_close.png'),
  region_back: require('@images/common/icon_advanced_options_back.png'),
  region_next: require('@images/common/icon_advanced_options_next.png'),
  region_check: require('@images/common/icon_advanced_options_check.png'),
  login_show_passwd: require('@images/common/icon_login_show_passwd.png'),
  to_eland_green: require('@images/common/to_eland_green.png'),
  login_hide_passwd: require('@images/common/icon_login_hide_passwd.png'),
  icon_goback_black: require('@images/common/icon_goback_black.png'),
  icon_goback_white: require('@images/common/icon_goback_white.png'),
  femaleIcon: require('@images/common/femaleIcon.png'),
  maleIcon: require('@images/common/maleIcon.png'),
  setting_green: require('@images/common/setting_green.png'),
  col_dot_grey: require('@images/common/col_dot_grey.png'),
  move_back: require('@images/common/move_back.png'),
  move_forward: require('@images/common/move_forward.png'),
  playIcon: require('@images/common/playIcon.png'),
  reward: require('@images/common/reward.png'),
  stop_sound: require('@images/common/stop_sound.png'),
  search_black: require('@images/common/search_black.png'),
  link: require('@images/common/link.png'),
  navigation_right: require('@images/common/navigation_right.png'),
  col_dot: require('@images/common/col_dot.png'),
  titleCom_share: require('@images/common/titleCom_share.png'),
  album_logo: require('@images/common/album_logo.png'),
  qr_code_icon: require('@images/common/qr_code_icon.png'),
  hlandLogo: require('@images/common/hlandLogo.png'),
  col_dot_black: require('@images/common/col_dot_black.png'),
  prayer_like_black: require('@images/common/prayer_like_black.png'),
  prayer_like_green: require('@images/common/prayer_like_green.png'),
  prayer_confirm_black: require('@images/common/prayer_confirm_black.png'),
  tag_icon: require('@images/common/tag_icon.png'),
  prayer_confirm_green: require('@images/common/prayer_confirm_green.png'),
  prayer: require('@images/common/prayer.png'),
  go_right_pick: require('@images/common/go_right_pick.png'),
  row_dot: require('@images/common/row_dot.png'),
  reward_white: require('@images/common/reward_white.png'),
  modal_close: require('@images/common/modal_close.png'),
  fontSize: require('@images/common/fontSize.png'),
  fontColor: require('@images/common/fontColor.png'),
  fontSize_sel: require('@images/common/fontSize_sel.png'),
  fontColor_sel: require('@images/common/fontColor_sel.png'),
  camera: require('@images/common/camera.png'),
  audio_play: require('@images/common/audio_play.png'),
  audioOrVideo_add: require('@images/common/audioOrVideo_add.png'),
  hide_keyboard: require('@images/common/hide_keyboard.png'),
  bible: require('@images/common/bible.png'),
  Bibleverse: require('@images/common/Bibleverse.png'),
  Bibleverse_green: require('@images/common/Bibleverse_green.png'),
  bible_fs: require('@images/common/bible_fs.png'),
  gray_green_bigBg: require('@images/common/gray_green_bigBg.png'),
  audio_move_back: require('@images/common/audio_move_back.png'),
  audio_move_forward: require('@images/common/audio_move_forward.png'),
  audio_move_play: require('@images/common/audio_move_play.png'),
  audio_move_close: require('@images/common/audio_move_close.png'),
  navigation_right_blue: require('@images/common/navigation_right_blue.png'),
  add_pink: require('@images/common/add_pink.png'),
  gray_close: require('@images/common/gray_close.png'),
  share_more: require('@images/common/share_more.png'),
  share_link: require('@images/common/share_link.png'),
  hland_friends: require('@images/common/hland_friends.png'),
  white_ture: require('@images/common/white_ture.png'),
  lock_pink: require('@images/common/lock_pink.png'),
  setting_black: require('@images/common/setting_black.png'),
  church_Color_green: require('@images/common/church_Color_green.png'),
  church_Color: require('@images/common/church_Color.png'),
  bible_fs_green: require('@images/common/bible_fs_green.png'),
  devotion_book_num: require('@images/common/devotion_book_num.png'),
  ture_green: require('@images/common/ture_green.png'),
  lock_blue: require('@images/common/lock_blue.png'),
  go_right_black: require('@images/common/go_right_black.png'),
  bin: require('@images/common/bin.png'),
  send: require('@images/common/send.png'),
  checkBox_na: require('@images/common/checkBox_na.png'),
  checkBox_a: require('@images/common/checkBox_a.png'),
  radio_true: require('@images/common/radio_true.png'),
  radio_false: require('@images/common/radio_false.png'),
  prayer_group_search: require('@images/common/prayer_group_search.png'),
  signIn_1: require('@images/common/signIn_1.png'),
  signIn_2: require('@images/common/signIn_2.png'),
  signIn_3: require('@images/common/signIn_3.png'),
  signIn_4: require('@images/common/signIn_4.png'),
  signIn_5: require('@images/common/signIn_5.png'),
  signIn_6: require('@images/common/signIn_6.png'),
  signIn_7: require('@images/common/signIn_7.png'),
  signIn_8: require('@images/common/signIn_8.png'),
  signIn_9: require('@images/common/signIn_9.png'),
  signIn_10: require('@images/common/signIn_10.png'),
  signIn_11: require('@images/common/signIn_11.png'),
  signIn_12: require('@images/common/signIn_12.png'),
};

const login = {
  login_banner: require('@images/login/login_banner.png'),
  login_ios: require('@images/login/login_ios.png'),
  login_google: require('@images/login/login_google.png'),
  login_email: require('@images/login/login_email.png'),
  register_topbar: require('@images/login/register_topbar.png'),
};

const home = {
  home_search_icon: require('@images/home/search_icon.png'),
  home_swipper: require('@images/home/home_swipper.png'),
  toScrollTop: require('@images/home/toScrollTop.png'),
  home_visibility: require('@images/home/home_visibility.png'),
  black_thumb_up: require('@images/home/black_thumb_up.png'),
  blue_thumb_up: require('@images/home/blue_thumb_up.png'),
  green_thumb_up: require('@images/home/green_thumb_up.png'),
  share_small: require('@images/home/share_small.png'),
  black_share: require('@images/home/black_share.png'),
  green_comment: require('@images/home/green_comment.png'),
  black_comment: require('@images/home/black_comment.png'),
  green_share: require('@images/home/green_share.png'),
  blogDetail_self_BG: require('@images/home/blogDetail_self_BG.png'),
  blog_auth_icon: require('@images/home/blog_auth_icon.png'),
  home_feature_bgImg: require('@images/home/home_feature_bgImg.png'),
  singIn_icon: require('@images/home/singIn_icon.png'),
  signBg: require('@images/home/signBg.png'),
  sign_modal: require('@images/home/sign_modal.png'),
  singIn_close: require('@images/home/singIn_close.png'),
  sign_top_logo: require('@images/home/sign_top_logo.png'),
  sign_record_item: require('@images/home/sign_record_item.png'),
  create_blog_success: require('@images/home/create_blog_success.png'),
};

const personal = {
  personal_top_bgImg: require('@images/personal/personal_top_bgImg.png'),
  personal_top_goback: require('@images/personal/personal_top_goback.png'),
  personal_top_contact: require('@images/personal/personal_top_contact.png'),
  personal_top_more: require('@images/personal/personal_top_more.png'),
  personal_top_dropMore: require('@images/personal/personal_top_dropMore.png'),
  personal_top_followIcon: require('@images/personal/personal_top_followIcon.png'),
  personal_top_vipIcon: require('@images/personal/personal_top_vipIcon.png'),
  personal_top_merrits: require('@images/personal/personal_top_merrits.png'),
  personal_top_shekels: require('@images/personal/personal_top_shekels.png'),
  personal_top_localBG: require('@images/personal/personal_top_localBG.png'),
  chat_green: require('@images/personal/chat_green.png'),
  arrow_right_blue: require('@images/personal/arrow_right_blue.png'),
  personal_top_styleSign: require('@images/personal/personal_top_styleSign.png'),
  personal_top_organization: require('@images/personal/personal_top_organization.png'),
  personal_top_goback_black: require('@images/personal/personal_top_goback_black.png'),
  personal_top_contact_black: require('@images/personal/personal_top_contact_black.png'),
  personal_top_moreIcon_black: require('@images/personal/personal_top_moreIcon_black.png'),
  personal_top_tabAdd: require('@images/personal/personal_top_tabAdd.png'),
  personal_top_category: require('@images/personal/personal_top_category.png'),
  editer_pink: require('@images/personal/editer_pink.png'),
  setting_icon: require('@images/personal/setting_icon.png'),
  photograph_personal: require('@images/personal/photograph_personal.png'),
  invite_footer: require('@images/personal/invite_footer.png'),
  personal_setting_bg: require('@images/personal/personal_setting_bg.png'),
  personal_add_group: require('@images/personal/personal_add_group.png'),
  personal_eland_btn: require('@images/personal/personal_eland_btn.png'),
  download_circle: require('@images/personal/download_circle.png'),
  apple_store_download: require('@images/personal/apple_store_download.png'),
  google_play_download: require('@images/personal/google_play_download.png'),
  personal_right: require('@images/personal/personal_right.png'),
  personal_eland: require('@images/personal/personal_eland.png'),
  devotion_item_bg: require('@images/personal/devotion_item_bg.png'),
  personal_file: require('@images/personal/personal_file.png'),
  church_green: require('@images/personal/church_green.png'),
  invitefrds: require('@images/personal/invitefrds.png'),
  invitefrds_bg: require('@images/personal/invitefrds_bg.png'),
  white_share: require('@images/personal/white_share.png'),
  shareFrds: require('@images/personal/shareFrds.png'),
  support_bg: require('@images/personal/support_bg.png'),
  supportFrame: require('@images/personal/supportFrame.png'),
  supportFrame2: require('@images/personal/supportFrame2.png'),
  supportFrame3: require('@images/personal/supportFrame3.png'),
  supportFrame4: require('@images/personal/supportFrame4.png'),
  supportFrame5: require('@images/personal/supportFrame5.png'),
  supportFrame6: require('@images/personal/supportFrame6.png'),
  profile_share_black: require('@images/personal/profile_share_black.png'),
  profile_share: require('@images/personal/profile_share.png'),
  supportBut: require('@images/personal/supportBut.png'),
  fansT: require('@images/personal/fansT.png'),
  setting_pink: require('@images/personal/setting_pink.png'),
};

const community = {
  communityBG: require('@images/community/communityBG.png'),
  forum_item_add: require('@images/community/forum_item_add.png'),
  post_forum: require('@images/community/post_forum.png'),
  community_up_black: require('@images/community/community_up_black.png'),
  community_share_black: require('@images/community/community_share_black.png'),
  community_down_green: require('@images/community/community_down_green.png'),
  community_up_green: require('@images/community/community_up_green.png'),
  community_see_black: require('@images/community/community_see_black.png'),
  community_down_black: require('@images/community/community_down_black.png'),
  community_comment_black: require('@images/community/community_comment_black.png'),
  community_post: require('@images/community/community_post.png'),
  community_topic: require('@images/community/community_topic.png'),
  community_contact: require('@images/community/community_contact.png'),
  closeButton: require('@images/community/closeButton.png'),
  forum_top: require('@images/community/forum_top.png'),
  forum_manager: require('@images/community/forum_manager.png'),
  add_post_icon: require('@images/community/add_post_icon.png'),
  forum_home: require('@images/community/forum_home.png'),
};

const quick = {
  devotionRecord_bgImg: require('@images/quick/devotionRecord_bgImg.png'),
  setting_blue: require('@images/quick/setting_blue.png'),
  my_history_topBG: require('@images/quick/my_history_topBG.png'),
  cycle_lock: require('@images/quick/cycle_lock.png'),
  cycle_original: require('@images/quick/cycle_original.png'),
  cycle_top: require('@images/quick/cycle_top.png'),
  Prayer_bg_img: require('@images/quick/Prayer_bg_img.png'),
  blog_signature: require('@images/quick/blog_signature.png'),
  post_prayer: require('@images/quick/post_prayer.png'),
  group_more: require('@images/quick/group_more.png'),
  prayer_like_35: require('@images/quick/prayer_like_35.png'),
  prayer_notLike_35: require('@images/quick/prayer_notLike_35.png'),
  myPost_topic: require('@images/quick/myPost_topic.png'),
  prayer_guide: require('@images/quick/prayer_guide.png'),
  prayer_invite: require('@images/quick/prayer_invite.png'),
  prayer_group_gray: require('@images/quick/prayer_group_gray.png'),
  group_add_gray: require('@images/quick/group_add_gray.png'),
  prayer_exit_red: require('@images/quick/prayer_exit_red.png'),
  group_reduce_gray: require('@images/quick/group_reduce_gray.png'),
  prayer_conservator_green: require('@images/quick/prayer_conservator_green.png'),
  prayer_conservator_gray: require('@images/quick/prayer_conservator_gray.png'),
  prayer_camera: require('@images/quick/prayer_camera.png'),
  prayer_search: require('@images/quick/prayer_search.png'),
  prayer_private_lock: require('@images/quick/prayer_private_lock.png'),
  prayer_private_unlock: require('@images/quick/prayer_private_unlock.png'),
  group_add: require('@images/quick/group_add.png'),
  keyboard_arrow_right: require('@images/quick/keyboard_arrow_right.png'),
  devotion_bg_img: require('@images/quick/devotion_bg_img.png'),
  myPost_logo: require('@images/quick/myPost_logo.png'),
  devotion_bg_img2: require('@images/quick/devotion_bg_img2.png'),
  myPost_numbers: require('@images/quick/myPost_numbers.png'),
  spiritual_diet_book: require('@images/quick/spiritual_diet_book.png'),
  Bible_book: require('@images/quick/Bible_book.png'),
  Wildernessmanna_book: require('@images/quick/Wildernessmanna_book.png'),
  erdao_self_built_book: require('@images/quick/erdao_self_built_book.png'),
  devotion_record_book: require('@images/quick/devotion_record_book.png'),
  devotion_note_active: require('@images/quick/devotion_note_active.png'),
  devotion_note_gray: require('@images/quick/devotion_note_gray.png'),
  close_white: require('@images/quick/close_white.png'),
  bible_bar_copy: require('@images/quick/bible_bar_copy.png'),
  bible_bar_close: require('@images/quick/bible_bar_close.png'),
  bible_bar_hilight: require('@images/quick/bible_bar_hilight.png'),
  bible_bar_note: require('@images/quick/bible_bar_note.png'),
  bible_bar_devotion: require('@images/quick/bible_bar_devotion.png'),
  devotionEditor_bg: require('@images/quick/devotionEditor_bg.png'),
  devotion_edit_info: require('@images/quick/devotion_edit_info.png'),
  devotion_edit_add_photo: require('@images/quick/devotion_edit_add_photo.png'),
  sermonote_bg: require('@images/quick/sermonote_bg.png'),
  build_d: require('@images/quick/build_d.png'),
  scanner_sermonote: require('@images/quick/scanner_sermonote.png'),
  post_menu_bg: require('@images/quick/post_menu_bg.png'),
  myPost_menu_close: require('@images/quick/myPost_menu_close.png'),
  myPost_menu_open: require('@images/quick/myPost_menu_open.png'),
  sermonote_add: require('@images/quick/sermonote_add.png'),
  sermonote_bg_bar: require('@images/quick/sermonote_bg_bar.png'),
  sermonote_scan_pink: require('@images/quick/sermonote_scan_pink.png'),
  sermonote_bottom_bg: require('@images/quick/sermonote_bottom_bg.png'),
  sermonote_bible: require('@images/quick/sermonote_bible.png'),
  sermonote_body_title: require('@images/quick/sermonote_body_title.png'),
  delete_bible: require('@images/quick/delete_bible.png'),
  blog_report: require('@images/quick/blog_report.png'),
  blog_report_green: require('@images/quick/blog_report_green.png'),
  sermonote_detail_bg1: require('@images/quick/sermonote_detail_bg1.png'),
  sermonote_detail_bg2: require('@images/quick/sermonote_detail_bg2.png'),
  arrow_down: require('@images/quick/arrow_down.png'),
  devotion_bible_pink: require('@images/quick/devotion_bible_pink.png'),
  blog_defaults_headP: require('@images/quick/blog_defaults_headP.png'),
  prayerEdti_bible: require('@images/quick/prayerEdti_bible.png'),
  prayerEdti_img: require('@images/quick/prayerEdti_img.png'),
  prayerEdti_tag: require('@images/quick/prayerEdti_tag.png'),
  prayerEdti_keyboard: require('@images/quick/prayerEdti_keyboard.png'),
  prayer_bg: require('@images/quick/prayer_bg.png'),
  prayerLine: require('@images/quick/prayerLine.png'),
  prayerGroup_add: require('@images/quick/prayerGroup_add.png'),
  prayerShow_list: require('@images/quick/prayerShow_list.png'),
  prayerShow_answered: require('@images/quick/prayerShow_answered.png'),
  prayerShow_edit: require('@images/quick/prayerShow_edit.png'),
  prayerShow_answered_active: require('@images/quick/prayerShow_answered_active.png'),
  sermonote_arrow_forward_green: require('@images/quick/sermonote_arrow_forward_green.png'),
  sermonote_arrow_forward_black: require('@images/quick/sermonote_arrow_forward_black.png'),
  prayer_white: require('@images/quick/prayer_white.png'),
  prayer_answer_down: require('@images/quick/prayer_answer_down.png'),
  close_big_prayer: require('@images/quick/close_big_prayer.png'),
  prayer_arrow_right: require('@images/quick/prayer_arrow_right.png'),
  prayer_answer_up: require('@images/quick/prayer_answer_up.png'),
};

const chat = {
  notification_bell: require('@images/chat/notification_bell.png'),
  notification_prayergroup: require('@images/chat/notification_prayergroup.png'),
  notification_shekels: require('@images/chat/notification_shekels.png'),
  chat_bg: require('@images/chat/chat_bg.png'),
  chat_emoji: require('@images/chat/chat_emoji.png'),
  chat_add: require('@images/chat/chat_add.png'),
  chat_camera: require('@images/chat/chat_camera.png'),
  chat_mircrophone: require('@images/chat/chat_mircrophone.png'),
  chat_group_editor: require('@images/chat/chat_group_editor.png'),
  chat_del_history: require('@images/chat/chat_del_history.png'),
  exit_group: require('@images/chat/exit_group.png'),
  group_report: require('@images/chat/group_report.png'),
  group_share_imgMin: require('@images/chat/group_share_imgMin.png'),
  group_share_link_btn: require('@images/chat/group_share_link_btn.png'),
  chat_frontAdmin: require('@images/chat/chat_frontAdmin.png'),
  group_share_copy_btn: require('@images/chat/group_share_copy_btn.png'),
  group_share_qrcode_btn: require('@images/chat/group_share_qrcode_btn.png'),
  add_groupUser: require('@images/chat/add_groupUser.png'),
  reduce_groupUser: require('@images/chat/reduce_groupUser.png'),
  chat_add_gray: require('@images/chat/chat_add_gray.png'),
  manager_icon: require('@images/chat/manager_icon.png'),
  chat_audio_play: require('@images/chat/chat_audio_play.png'),
  notice_bg: require('@images/chat/notice_bg.png'),
  chat_group_addPhoto: require('@images/chat/chat_group_addPhoto.png'),
  defualt_chatGroup_img: 'https://media.h.land/imgs/dancing_girls.jpg',
};

// icons end //

const getImage = () => ({
  ...bottomNavIcon,
  ...common,
  ...login,
  ...home,
  ...personal,
  ...community,
  ...quick,
  ...chat,
});

const getBaseImageUrl = () => {
  return '';
};

export default {getBaseImageUrl, ...getImage()};
